apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: {{ .Values.containerport }}
      targetPort: {{ .Values.containerport }}
      nodePort: {{ .Values.nodeport }}